spring:
  application:
    name: pos-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      enabled: true
      server:
        webflux:
          routes:
            - id: micro-server-pos-sale
              uri: lb://POS-SALE
              predicates:
                - Path=/api/v1/orders/**
            - id: micro-server-pos-plus
              uri: lb://POS-PLUS
              predicates:
                - Path=/api/v1/products/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    webclient:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
